### PR TITLE
Fix menu items reorder

### LINKED ISSUE #654: Dashboard > Configuration > Navigation  > Navbar : issue reordering Navbar > Menu Items
Trying to reorder the menu items in the Navbar, then save.
Reordering doesn't work sometimes.

For example moving the 2nd category to the 1st position is not saved.

### PR DESCRIPTION
**Pull request by mmarkusik**
I want to merge this change because it fixes menu items reordering.

[SALEOR-860](https://app.clickup.com/t/2549495/SALEOR-860)
Fix #654

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-860 Moving menu items does not work correctly](https://app.clickup.com/t/2549495/SALEOR-860)

**Review by krzysztofwolski — CHANGES_REQUESTED** [review]
There are still issues.

Create menu like this and save:
image

Rearrange items:
image

After save order is changed:
image

**Comment by mmarkusik** [comment]
Confirmed with @korycins that the remaining irregularities are actually a backend issue, opened an [issue](https://app.clickup.com/t/2549495/SALEOR-1647) in clickup

**Comment by maarcingebala** [comment]
@mmarkusik @krzysztofwolski The backend issue that Magda reported is now fixed (https://github.com/mirumee/saleor/pull/6523), can we merge this one as well?

**Review by AlicjaSzu — APPROVED** [review]

**Comment by krzysztofwolski** [comment]
I still have issues with reordering multiple elements.

1. Create menu:
image

2. Reorder multiple elements and click save
image

3. After clicking save entries shuffle:
image

@d-wysocki @mmarkusik

**Comment by krzysztofwolski** [comment]
Since its not clear if its front or backend side, I'm adding blocked tak. Let me know if the situation clarify

**Pull request closed without merging**
