### PR TITLE
Use alerts and notifications from macaw

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it adds usage of notifications and alerts from macaw rather than internal code.

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-3401 Extract alert boxes to Macaw UI](https://app.clickup.com/t/2549495/SALEOR-3401)

**Comment by patrys** [comment]
Task linked: [SALEOR-3400 Extract notifications to Macaw UI](https://app.clickup.com/t/2549495/SALEOR-3400)

**Comment by patrys** [comment]
Task linked: [SALEOR-3287 Use Macaw-UI in both Saleor Cloud and Saleor Dashboard](https://app.clickup.com/t/2549495/SALEOR-3287)

**Review by SektorDV — COMMENTED** [review]
there seems to be a lot of cases where alerts are followed by the `<FormSpacer />` component. isn't this a case for maybe adding an optional prop to `<Alert />` that would append the spacer to the alert without adding the extra `React.Fragment`?

**Review by SektorDV — APPROVED** [review]

**Comment by dominik-zeglen** [comment]
Yes and no, I'm not a fan of adding margins to components because most of the time they get overriden half of the time. On the other hand code isn't DRY now so it's not cool either. Best idea I can come up is to create `LimitReachedAlert` component which would encapsulate spacer and hide some props.

**Comment by dominik-zeglen** [comment]
Yes and no, I'm not a fan of adding margins to components because most of the time they get overriden half of the time. On the other hand code isn't DRY now so it's not cool either. Best idea I can come up is to create `LimitReachedAlert` component which would encapsulate spacer and hide some props.

**Review by SektorDV — APPROVED** [review]

**Review by jwm0 — APPROVED** [review]

**Pull request merged**
