### PR TITLE
Fix handle attribute errors

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it allows user to actually get to know which attribute didn't pass validation.

**PR intended to be tested with API branch:** master

### Screenshots
Screenshot 2020-09-29 at 16 30 34
Screenshot 2020-09-29 at 17 06 11

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-1181 Creating Product does not display attribute error](https://app.clickup.com/t/2549495/SALEOR-1181)

**Review by orzechdev — APPROVED** [review]

**Review by AlicjaSzu — APPROVED** [review]

**Comment by mlamperski** [comment]
User doesn't observe validation process after choosing only Product Type.

**Comment by patrys** [comment]
Task linked: [SALEOR-1186 Handle attribute errors in product pages](https://app.clickup.com/t/2549495/SALEOR-1186)

**Comment by mlamperski** [comment]
User cannot save new product, when None for Attribute was chosen.
Steps to reproduce the problem:
1. https://fix-handle-attribute-errors.dashboard.saleor.rocks/products/add
2. Use product type Beer
3. Add Name and SKU
4. Select None from dropdown in ABV attribute
5. Try to save

RESULT: ABV is highlighted and blocks saving, even if attribute is not required.
EXPECTED RESULT: User should be able to save product

macOs/Chrome

**Review by mlamperski — APPROVED** [review]
Tested. Connected bug with creation a variant without attributes already reported on SALEOR-1272.

**Review by mmarkusik — APPROVED** [review]

**Pull request merged**
