### PR TITLE
tests for warehouses in checkout

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because I created tests for click and collect

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-4430 Create tests for click and collect](https://app.clickup.com/t/2549495/SALEOR-4430)

**Review by jwm0 — APPROVED** [review]
Looks good but the CI E2E test run fails, I assume it's nothing to do with these changes?

**Comment by eCzerniak** [comment]
> Looks good but the CI E2E test run fails, I assume it's nothing to do with these changes?

As far as I know, test for navigations are broken because of problem with permissions for giftCards and there is a known bug for sales.

**Review by bmigirl — APPROVED** [review]

**Review by eCzerniak — CHANGES_REQUESTED** [review]
Test should create warehouse with public stock is creating private stock.

**Comment by karola312** [comment]
Test for private stock fixed, added test for local stock pickup only

**Review by eCzerniak — APPROVED** [review]

**Pull request merged**
