### PR TITLE
Handle Cloud limits

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it handles cloud limits. It's a feature branch, so everything was reviewed earlier.
Ref #1004 

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [x] This code contains UI changes
2. [x] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [x] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://limited.staging.saleor.cloud/graphql/

### CODE REVIEW

**Review by jwm0 — APPROVED** [review]

**Comment by patrys** [comment]
Task linked: [SALEOR-2297 Display limits in dashboard](https://app.clickup.com/t/2549495/SALEOR-2297)

**Review by pwgryglak — CHANGES_REQUESTED** [review]
Snackbars in dark mode need to be changed. Already discussed with @dominik-zeglen. Other than that everything seems to be in place.

**Review by pwgryglak — CHANGES_REQUESTED** [review]
Three things:
- Change the snackbars - my bad on that part white text has bad contrast and can be hard to read.
- Product page - SKU limit should be shown in variants card not above it - can be seen in designs. Also create variant button should be styled as disabled.
- Can't review if the "SKU limit will be reached" snacker in variant creator.

**Comment by dominik-zeglen** [comment]
> * Can't review if the "SKU limit will be reached" snacker in variant creator.

https://handle-limits.dashboard.saleor.rocks/storybook/index.html/?path=/story/views-products-create-multiple-variants--interactive

**Review by pwgryglak — APPROVED** [review]

**Pull request merged**
