### PR TITLE
Add embed plugin to editorjs

### PR DESCRIPTION
**Pull request by mociepka**
I want to merge this change because...

https://app.clickup.com/t/2549495/SALEOR-3354

**PR intended to be tested without any API branch:**

### Screenshots

image

### Pull Request Checklist

1. [x] This code contains UI changes
2. [x] All visible strings are translated with proper context including data-formatting
3. [x] Attributes `[data-test-id]` are added for new elements
4. [x] Changes are mentioned in the changelog
5. [x] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-3354 Add ability to include YouTube videos to product description](https://app.clickup.com/t/2549495/SALEOR-3354)

**Review by jwm0 — COMMENTED** [review]
Please check if it doesn't break current storefront.

**Review by piotrgrundas — APPROVED** [review]

**Comment by mociepka** [comment]
I updated editorjs-html version and SF works with it:
https://github.com/mirumee/saleor-storefront/pull/1047

**Comment by mociepka** [comment]
This PR is blocked by https://github.com/mirumee/saleor/pull/7365.

**Pull request merged**
