### PR TITLE
Make price rates views use parent shipping method channels instead of all

### PR DESCRIPTION
**Pull request by mmarkusik**
I want to merge this change because it makes the price / weight rates views use parent shipping zone channels instead of all. 

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [x] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://feature-variants-and-shipping-zones-per-channel.api.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-2553 Update managing shipping method's channel availability](https://app.clickup.com/t/2549495/SALEOR-2553)

**Comment by patrys** [comment]
Task linked: [SALEOR-2552 Allow assigning shipping zones to channels](https://app.clickup.com/t/2549495/SALEOR-2552)

**Review by jwm0 — APPROVED** [review]

**Review by dominik-zeglen — APPROVED** [review]

**Comment by dominik-zeglen** [comment]
What happened to types?

**Comment by maarcingebala** [comment]
@jwm0 @mmarkusik I suggest that we first merge this PR to the feature branch and then we'll do the QA, so that we have a full feature working on the feature branch.

**Pull request merged**
