### PR TITLE
Add global channel picker

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it adds global channel picker, replacing dialogs and setting active channel per view.

**PR intended to be tested with API branch:** master

### Screenshots
Screenshot 2020-11-19 at 11 22 35

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-1518 Add global multichannel picker to top bar](https://app.clickup.com/t/2549495/SALEOR-1518)

**Comment by krzysztofwolski** [comment]
@dominik-zeglen cannot access dashboard deployment, does it works for you?

**Comment by dominik-zeglen** [comment]
Oops

**Review by jwm0 — APPROVED** [review]

**Review by jwm0 — CHANGES_REQUESTED** [review]
I went through the app and it looks like you can only change the channel on the initial dashboard view (and subpages where it has an effect), it makes more sense to me for this option to be enabled throughout the application so the user can freely switch between channels on any subpage.

**Comment by dominik-zeglen** [comment]
> I went through the app and it looks like you can only change the channel on the initial dashboard view, it makes more sense to me for this option to be enabled throughout the application so the user can freely switch between channels on subpages.

Business requirements.

**Review by jwm0 — APPROVED** [review]

**Review by orzechdev — APPROVED** [review]

**Pull request merged**
