### PR TITLE
SALEOR-2266 - Added contrast sidebar logos for dark mode

### PR DESCRIPTION
**Pull request by SektorDV**
I want to merge this change because it resolves the issue with low contrast sidebar logos in dark mode.

### Pull Request Checklist

1. [x] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-2266 Saleor logo in dark mode is not visible](https://app.clickup.com/t/2549495/SALEOR-2266)

**Comment by dominik-zeglen** [comment]
Care to make a PR here too?
https://github.com/mirumee/macaw-ui

**Review by dominik-zeglen — APPROVED** [review]

**Comment by SektorDV** [comment]
> Care to make a PR here too?
> https://github.com/mirumee/macaw-ui

sure thing, i'll add it to my backlog

**Review by pwgryglak — CHANGES_REQUESTED** [review]
It need to be the logo with the dash.

**Comment by patrys** [comment]
Let's give those commits nicer titles so they look like the rest of our history.

**Review by mmarkusik — APPROVED** [review]

**Review by eCzerniak — APPROVED** [review]

**Review by pwgryglak — CHANGES_REQUESTED** [review]
Wrong logo used in sidebar

**Review by pwgryglak — APPROVED** [review]

**Pull request merged**
