### PR TITLE
product pricing

### PR DESCRIPTION
**Pull request by AlicjaSzu**
I want to merge this change because...

**PR intended to be tested with API branch:** feature/multichannel-multicurrency

### Screenshots
Screenshot 2020-09-15 at 21 30 34

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-164 Use two mutations to create simple products](https://app.clickup.com/t/2549495/SALEOR-164)

**Comment by patrys** [comment]
Task linked: [SALEOR-92 Update variant page for configurable products - view](https://app.clickup.com/t/2549495/SALEOR-92)

**Comment by patrys** [comment]
Task linked: [SALEOR-1032 pricing card - add mutation](https://app.clickup.com/t/2549495/SALEOR-1032)

**Comment by patrys** [comment]
Task linked: [SALEOR-1033 Update variant page for configurable products - components](https://app.clickup.com/t/2549495/SALEOR-1033)

**Review by orzechdev — APPROVED** [review]

**Pull request merged**
