### PR TITLE
gift cards in checkout

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because I created tests for gift cards in checkout

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-4396 Add giftcards to checkout](https://app.clickup.com/t/2549495/SALEOR-4396)

**Review by dominik-zeglen — APPROVED** [review]

**Review by jwm0 — APPROVED** [review]

**Review by eCzerniak — CHANGES_REQUESTED** [review]
Please correct test cases, now there are: 
1. should buy product with gift card,
2. should enable gift card,
3. should disable giftCard, 
and we agreed that it should be just: 
1. should buy product with gift card - where we can check if giftCard is enabled,.
2. should disable giftCard - and there should be check if when we will done whole checkout the amount is not changed.

**Comment by karola312** [comment]
Test cases are corrected

**Review by eCzerniak — CHANGES_REQUESTED** [review]
Not all changes have been made that were listed in an earlier comment.

**Review by eCzerniak — APPROVED** [review]

**Pull request merged**
