### PR TITLE
Order confirmation

### PR DESCRIPTION
**Pull request by krzysztofwolski**
https://app.clickup.com/2549495/v/l/li/32025488

New feature: Order confirmations

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://feature-order-confirmation.api.saleor.rocks/graphql/

### CODE REVIEW

**Comment by krzysztofwolski** [comment]
Added changelog and feature is ready for QA @mlamperski

**Comment by mlamperski** [comment]
Issue: Unforfirmed label is not visible on Dark Mode
image
Expected:
image
System: macOs/Chrome

**Comment by mlamperski** [comment]
ISSUE:
Trying to to confirm Order which is: Unpayed, Unconfirmed and Unfulfilled generates error.
Example https://feature-order-confirmation.dashboard.saleor.rocks/orders/T3JkZXI6MjU%3D
STEPS:
Open example order
Do not Fulfill the order
Click Confirm Order button
image

Not sure about expected behaviour, case need to be discussed.
System: macOs/Chrome

**Review by mlamperski — APPROVED** [review]

**Review by mlamperski — APPROVED** [review]
Tests finished. No more issues were found.

**Review by maarcingebala — APPROVED** [review]

**Pull request merged**
