### PR TITLE
Use rem as a spacing unit

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it changes default spacing unit from `8px` to `0.8rem`.
Note: built on top of #1100 

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [x] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-3288 Use rem as a spacing unit in dashboard](https://app.clickup.com/t/2549495/SALEOR-3288)

**Comment by patrys** [comment]
Task linked: [SALEOR-3287 Use Macaw-UI in both Saleor Cloud and Saleor Dashboard](https://app.clickup.com/t/2549495/SALEOR-3287)

**Review by pwgryglak — APPROVED** [review]
I looked through the storybook - there are some inconsistencies in webhook view for example that needs to be fixed - otherwise looks ok.

**Review by jwm0 — CHANGES_REQUESTED** [review]
I see a number of issues with font sizing in UI:

Before:
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

**Comment by dominik-zeglen** [comment]
Nice catch

**Review by orzechdev — APPROVED** [review]

**Review by jwm0 — APPROVED** [review]

**Pull request merged**
