### PR TITLE
Add transaction reference input at order page

### PR DESCRIPTION
**Pull request by karolinakuzniewicz**
I want to merge this change because...

https://app.clickup.com/t/2549495/SALEOR-1387

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://saleor-1385-external-payment-reference.api.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-1384 Add input to provide rating value in dashboard](https://app.clickup.com/t/2549495/SALEOR-1384)

**Review by mmarkusik — APPROVED** [review]

**Comment by krzysztofwolski** [comment]
Ref https://github.com/mirumee/saleor/pull/6320

**Comment by krzysztofwolski** [comment]
Branch needs rebasing to the multichannel.

**Comment by krzysztofwolski** [comment]
No space between cards on order details 
image

**Comment by krzysztofwolski** [comment]
Draft order cannot be finalized without page refresh. But it's known bug which is assigned https://app.clickup.com/t/2549495/SALEOR-1601

**Comment by krzysztofwolski** [comment]
I was able to successfully add payment reference: 
image

**Review by krzysztofwolski — APPROVED** [review]

**Pull request merged**
