### PR TITLE
[chore] Update dependencies, fix warnings during tests

### PR DESCRIPTION
**Pull request by krzysztofwolski**
I want to merge this change because once in a while every project needs a little bit of love.

Before:
`npm i`
```
found 337 vulnerabilities (331 low, 6 high)
```
`npm run test` printing wall of warnings

After:
```
found 309 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

`npm run test` + having only one issue left ;) 

I advise to try out test deployment to check if there is any visual issue.

Other changes:
- fixed fixture images in one of the stories
- translation pages throw less errors in the console
- removed unused testcafe leftovers
- fixed smaller issues after bumping TS version

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Review by jwm0 — APPROVED** [review]

**Review by orzechdev — APPROVED** [review]

**Comment by krzysztofwolski** [comment]
Branch passed to QA for regression testing

**Comment by mlamperski** [comment]
Testing in Progress. 
Text for invoices is moved
Screenshot 2020-11-25 at 17 45 21

**Review by AlicjaSzu — APPROVED** [review]

**Comment by mlamperski** [comment]
Tested on deployed environment. No more issues detected.

**Comment by krzysztofwolski** [comment]
Fixed 
image

**Pull request merged**
