### PR TITLE
Do not allow negative values and display errors

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it fixes multiple bugs connected to negative prices, quantities and weights.

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Review by orzechdev — APPROVED** [review]

**Comment by patrys** [comment]
Task linked: [SALEOR-1244 [Generic error][Variants] Errors from Price, Price Cost and Quantity don't give inforrnation to the user](https://app.clickup.com/t/2549495/SALEOR-1244)

**Review by AlicjaSzu — APPROVED** [review]

**Comment by mlamperski** [comment]
Writing long number, e.g. '21421412421412412421421421421421412422142152235' in Quantity still generates error. Similar behavior as in reported bug. Error popup is visible.
image

**Comment by maarcingebala** [comment]
@mlamperski This error from the screenshot above is a backend issue. I'll add a task to fix in the backend, but I think we can merge this frontend PR anyway.

**Review by mlamperski — APPROVED** [review]
Tested positive. Other issues connected to the incorrect behavior has been already reported.

**Pull request merged**
