### PR TITLE
1721 - add refunds miscellaneous view

### PR DESCRIPTION
**Pull request by orzechdev**
I want to merge this change because... it replaces the payment refund dialog with a dedicated order refund page.

**PR intended to be tested with API branch:**  master

### Screenshots

Zrzut ekranu 2020-11-25 o 14 44 24

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Review by krzysztofwolski — CHANGES_REQUESTED** [review]
Unconsistent currency formatting - on the screenshot half of labels is using "zł" and other half "pln".

**Comment by orzechdev** [comment]
@krzysztofwolski this inconsistency is on design also

**Comment by patrys** [comment]
Task linked: [SALEOR-1721 Create new view for Miscellaneous Refunds](https://app.clickup.com/t/2549495/SALEOR-1721)

**Comment by krzysztofwolski** [comment]
@orzechdev OK, carry on. Unifiying currency display will be done later.

**Review by krzysztofwolski — APPROVED** [review]
Ok, parts missing from the backend will be updated later on when API will catch up

**Review by AlicjaSzu — APPROVED** [review]

**Comment by orzechdev** [comment]
Feature branch https://github.com/mirumee/saleor-dashboard/pull/870

**Pull request merged**
