### PR TITLE
fix homepage select/product update form

### PR DESCRIPTION
**Pull request by AlicjaSzu**
I want to merge this change because...

- fixes homepage channels select
- fixes product update form

**PR intended to be tested with API branch:** feature/multichannel-multicurrency

### Screenshots

Screenshot 2020-11-02 at 10 48 29

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://feature-multichannel-multicurrency.api.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-1497 [BUG] Cannot update simple product after SKU validation error](https://app.clickup.com/t/2549495/SALEOR-1497)

**Comment by patrys** [comment]
Task linked: [SALEOR-1501 [BUG] Dropdown on Home page doesn't inform about other channels](https://app.clickup.com/t/2549495/SALEOR-1501)

**Review by orzechdev — APPROVED** [review]

**Comment by mlamperski** [comment]
ISSUE: Dropdown for channel shows incorrectly.
image
System: macOs/Chrome
Env: Deployed test environment

**Comment by mlamperski** [comment]
ISSUE: Dropdown for channels interfere with User's dropdown items.
image
System: macOs/Chrome
Env: Deployed test environment

**Comment by mlamperski** [comment]
Tested on deployed environment. Reported issues does not occur any more.

**Review by mmarkusik — APPROVED** [review]

**Pull request merged**
